const Repos = {
  agenda: {
    list() { return DB.getAppointments(); },
    get(id) { return DB.getAppointments().find(a => a.id === id) || null; },
    byDate(date) { return DB.getAppointmentsByDate(date); },
    byDateRange(start, end) { return DB.getAppointmentsByDateRange(start, end); },
    byProfessional(prof, date) { return DB.getAppointmentsByProfessional(prof, date); },
    upcoming(limit) { return DB.getUpcomingAppointments(limit); },
    create(data) { return DB.addAppointment(data); },
    update(id, data) { return DB.updateAppointment(id, data); },
    remove(id) { DB.deleteAppointment(id); },
    today() { return DB._today(); },
  },
  clientes: {
    list() { return DB.getClients(); },
    get(id) { return DB.getClient(id); },
    search(query) { return DB.searchClients(query); },
    create(data) { return DB.addClient(data); },
    update(id, data) { return DB.updateClient(id, data); },
    remove(id) { DB.deleteClient(id); },
    history: {
      list(clientId) { return DB.getServiceHistory(clientId); },
      create(clientId, data) { return DB.addServiceHistory(clientId, data); },
      remove(clientId, entryId) { return DB.deleteServiceHistory(clientId, entryId); },
    },
  },
  studio: {
    settings: {
      get() { return DB.getSettings(); },
      save(data) { return DB.saveSettings(data); },
    },
    professionals: {
      list() { return DB.getProfessionals(); },
      active() { return DB.getActiveProfessionals(); },
      label(id) { return DB.getProfessionalLabel(id); },
      commission(id) { return DB.getProfessionalCommission(id); },
      create(data) { return DB.addProfessional(data); },
      update(id, data) { return DB.updateProfessional(id, data); },
    },
    services: {
      list() { return DB.getServices(); },
      active() { return DB.getActiveServices(); },
      create(data) { return DB.addService(data); },
      update(id, data) { return DB.updateService(id, data); },
    },
    hours: {
      get() { return DB.getBusinessHours(); },
      save(data) { return DB.saveBusinessHours(data); },
    },
  },
  produtos: {
    list() { return DB.getProducts(); },
    get(id) { return DB.getProducts().find(p => p.id === id) || null; },
    active() { return DB.getActiveProducts(); },
    create(data) { return DB.addProduct(data); },
    update(id, data) { return DB.updateProduct(id, data); },
    categories: {
      list() { return DB.getCategories(); },
      active() { return DB.getActiveCategories(); },
      create(data) { return DB.addCategory(data); },
      update(id, data) { return DB.updateCategory(id, data); },
    },
    movements: {
      list(productId) { return DB.getMovements(productId); },
      create(data) { return DB.addMovement(data); },
    },
    sales: {
      list() { return DB.getSales(); },
      create(data) { return DB.addSale(data); },
    },
  },
  financeiro: {
    paymentMethods: {
      list() { return DB.getPaymentMethods(); },
      create(data) { return DB.addPaymentMethod(data); },
      update(id, data) { return DB.updatePaymentMethod(id, data); },
    },
    cashier: {
      open() { return DB.getOpenCashier(); },
      getOpen() { return DB.getOpenCashier(); },
      openCashier(data) { return DB.openCashier(data); },
      open(data) { return DB.openCashier(data); },
      close(id, data) { return DB.closeCashier(id, data); },
      closeCashier(id, data) { return DB.closeCashier(id, data); },
      list() { return DB._get('caixas'); },
    },
    ledger: {
      list(date, type) { return DB.getLedger(date, type); },
      create(data) { return DB.addLedger(data); },
    },
  },
  atendimento: {
    queue: {
      list() { return DB.getQueue(); },
      byStatus(status) { return DB.getQueueByStatus(status); },
      create(data) { return DB.addToQueue(data); },
      add(data) { return DB.addToQueue(data); },
      updateStatus(id, status) { return DB.updateQueueStatus(id, status); },
      updateEntry(id, data) { return DB.updateQueueEntry(id, data); },
      remove(id) { DB.removeFromQueue(id); },
      clear() { DB.clearTodayQueue(); },
      clearToday() { DB.clearTodayQueue(); },
    },
    revenueToday() { return DB.getTodayRevenue(); },
  },
  os: {
    list() { return DB.getOrdensServico(); },
    get(id) { return DB.getOrdemServico(id); },
    create(data) { return DB.addOrdemServico(data); },
    update(id, data) { return DB.updateOrdemServico(id, data); },
  },
  termos: {
    list() { return DB.getTermos(); },
    get(id) { return DB.getTermo(id); },
    byClient(clientId) { return DB.getTermosByClient(clientId); },
    create(data) { return DB.addTermo(data); },
    update(id, data) { return DB.updateTermo(id, data); },
  },
  vales: {
    list() { return DB.getVales(); },
    get(id) { return DB.getVale(id); },
    byClient(clientId) { return DB.getValesByClient(clientId); },
    activeByClient(clientId) { return DB.getValesAtivosByClient(clientId); },
    balance(clientId) { return DB.getClientValeBalance(clientId); },
    create(data) { return DB.addVale(data); },
    use(clientId, amount, operation, refId) { return DB.useVale(clientId, amount, operation, refId); },
    update(id, data) { return DB.updateVale(id, data); },
  },
  pacotes: {
    list() { return DB.getPacotes(); },
    get(id) { return DB.getPacote(id); },
    byClient(clientId) { return DB.getPacotesByClient(clientId); },
    activeByClientAndService(clientId, service) { return DB.getPacotesAtivosByClientAndService(clientId, service); },
    create(data) { return DB.addPacote(data); },
    use(clientId, service, refId, professional) { return DB.usePacote(clientId, service, refId, professional); },
    update(id, data) { return DB.updatePacote(id, data); },
  },
  comissoes: {
    list() { return DB.getComissoes(); },
    create(data) { return DB.addComissao(data); },
    update(id, data) { return DB.updateComissao(id, data); },
  },
  lembretes: {
    list() { return DB.getLembretes(); },
    get(id) { return DB.getLembrete(id); },
    create(data) { return DB.addLembrete(data); },
    update(id, data) { return DB.updateLembrete(id, data); },
    remove(id) { DB.deleteLembrete(id); },
  },
};
